(function(){
'use strict';
var CONFIG={texts:['hello，早上好',null,'生日快乐！'],targetDate:{year:2026,month:3,day:1,week:0},weekdays:['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],fireworkPalettes:[['#7dd3fc','#38bdf8','#0ea5e9','#fff'],['#f9a8d4','#f472b6','#ec4899','#fff'],['#fbbf24','#f59e0b','#fcd34d','#fff'],['#a78bfa','#c084fc','#e879f9','#fff'],['#34d399','#2dd4bf','#5eead4','#fff'],['#fb923c','#f97316','#fdba74','#fff']]};
function $(id){return document.getElementById(id);}
var canvas=$('fireworksCanvas'),ctx=canvas.getContext('2d'),typeText=$('typeText'),surpriseBtn=$('surpriseBtn'),startScreen=$('startScreen'),giftBox=$('giftBox'),dateRollerWrap=$('dateRollerWrap');
var rollerEls={year:$('numYear'),month:$('numMonth'),day:$('numDay'),week:$('numWeek')};
var bursts=[],rafId=null;
function resizeCanvas(){var w=window.innerWidth,h=window.innerHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}}
function initCanvas(){resizeCanvas();var t;window.addEventListener('resize',function(){clearTimeout(t);t=setTimeout(resizeCanvas,100);});}
function PixelBurst(cx,cy,palette){this.cx=cx;this.cy=cy;this.palette=palette;this.dots=[];this.alpha=1;this.decay=0.003;this.frame=0;var n=280+Math.floor(Math.random()*80);for(var i=0;i!==n;i++){var a=Math.random()*Math.PI*2,s=1+Math.random()*3;this.dots.push({x:0,y:0,vx:Math.cos(a)*s,vy:Math.sin(a)*s,friction:0.98+Math.random()*0.015,size:0.6+Math.random()*1.2,color:palette[Math.floor(Math.random()*palette.length)]});}}
PixelBurst.prototype.update=function(){this.frame++;for(var i=0;i!==this.dots.length;i++){var d=this.dots[i];d.x+=d.vx;d.y+=d.vy;d.vx*=d.friction;d.vy*=d.friction;}if(this.frame>=81){this.alpha-=this.decay;}return this.alpha>0;};
PixelBurst.prototype.draw=function(){ctx.save();for(var i=0;i!==this.dots.length;i++){var d=this.dots[i],x=this.cx+d.x,y=this.cy+d.y,dist=Math.sqrt(d.x*d.x+d.y*d.y),edgeFade=Math.max(0,1-dist/100);ctx.globalAlpha=this.alpha*edgeFade;ctx.fillStyle=d.color;ctx.beginPath();ctx.arc(x,y,d.size,0,Math.PI*2);ctx.fill();}ctx.restore();};
function fireworkLoop(){if(!canvas.width||!canvas.height){rafId=requestAnimationFrame(fireworkLoop);return;}ctx.clearRect(0,0,canvas.width,canvas.height);bursts=bursts.filter(function(b){b.update();b.draw();return b.alpha>0;});if(bursts.length){rafId=requestAnimationFrame(fireworkLoop);}}
function createFirework(){var w=canvas.width,h=canvas.height,cx=w*0.2+Math.random()*w*0.6,cy=h*0.25+Math.random()*h*0.5,palette=CONFIG.fireworkPalettes[Math.floor(Math.random()*CONFIG.fireworkPalettes.length)];bursts.push(new PixelBurst(cx,cy,palette));if(!rafId){rafId=requestAnimationFrame(fireworkLoop);}}
function showFireworks(){createFirework();setTimeout(createFirework,1200);setTimeout(createFirework,2400);setTimeout(createFirework,3600);setTimeout(createFirework,4800);}
function rollDateWheel(){dateRollerWrap.style.display='flex';dateRollerWrap.style.opacity='0';dateRollerWrap.style.transform='translateY(10px)';dateRollerWrap.style.transition='opacity 0.5s ease, transform 0.5s ease';dateRollerWrap.offsetHeight;dateRollerWrap.style.opacity='1';dateRollerWrap.style.transform='translateY(0)';var T=CONFIG.targetDate;[rollerEls.month,rollerEls.day,rollerEls.week].forEach(function(el){el.classList.add('rolling');});setTimeout(function(){rollerEls.month.textContent=String(T.month);rollerEls.day.textContent=String(T.day);rollerEls.week.textContent=CONFIG.weekdays[T.week];[rollerEls.month,rollerEls.day,rollerEls.week].forEach(function(el){el.classList.remove('rolling');});},700);setTimeout(function(){dateRollerWrap.style.opacity='0';setTimeout(function(){dateRollerWrap.style.display='none';typeText.textContent='';runTypeEffect();},500);},3600);}
var textIndex=0,charIndex=0,isDeleting=false;
function runTypeEffect(){if(textIndex===1&&CONFIG.texts[1]===null){typeText.textContent='';rollDateWheel();textIndex=2;return;}var current=CONFIG.texts[textIndex];if(!current){return;}var speed=isDeleting?70:110;if(isDeleting){charIndex--;}else{charIndex++;}typeText.textContent=current.substring(0,charIndex);if(!isDeleting&&charIndex===current.length){if(textIndex===CONFIG.texts.length-1){showFireworks();setTimeout(function(){surpriseBtn.classList.add('show');},800);return;}setTimeout(function(){isDeleting=true;},1300);}else if(isDeleting&&charIndex===0){isDeleting=false;textIndex++;}setTimeout(runTypeEffect,speed);}
function initGiftAnimation(){var page1=$('page1'),foldCornerWrap=$('foldCornerWrap');var isDragging=false,radius=100,centerX=0,centerY=0;function getBoxRect(){var r=giftBox.getBoundingClientRect();return{w:r.width,h:r.height,left:r.left,top:r.top};}var box=getBoxRect();window.addEventListener('resize',function(){box=getBoxRect();});function dragHandler(e){if(!isDragging){return;}var clientX=e.touches?e.touches[0].clientX:e.clientX,clientY=e.touches?e.touches[0].clientY:e.clientY;centerX=clientX-box.left;centerY=clientY-box.top;var dist=Math.hypot(centerX,centerY),maxDist=Math.hypot(box.w,box.h)*0.6;radius=Math.max(0,Math.min(100,100-dist/maxDist*100));page1.style.clipPath='circle('+radius+'% at '+centerX+'px '+centerY+'px)';}
function startDrag(e){if(e.touches){e.preventDefault();}isDragging=true;document.addEventListener('mousemove',dragHandler);document.addEventListener('mouseup',endDrag);document.addEventListener('touchmove',dragHandler,{passive:true});document.addEventListener('touchend',endDrag);}
function endDrag(){isDragging=false;document.removeEventListener('mousemove',dragHandler);document.removeEventListener('touchmove',dragHandler);document.removeEventListener('mouseup',endDrag);document.removeEventListener('touchend',endDrag);if(radius<=10){page1.style.opacity='0';foldCornerWrap.style.opacity='0';setTimeout(function(){page1.style.display='none';foldCornerWrap.style.display='none';},300);}}
foldCornerWrap.addEventListener('mousedown',startDrag);foldCornerWrap.addEventListener('touchstart',startDrag,{passive:false});}
surpriseBtn.addEventListener('click',function(){startScreen.style.transition='opacity 0.6s ease';startScreen.style.opacity='0';canvas.style.opacity='0';setTimeout(function(){startScreen.style.display='none';giftBox.style.display='block';initGiftAnimation();},500);});
initCanvas();runTypeEffect();
})();
